coverage:
  precision: 1
  range: "75...90"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%
github_checks:
  annotations: true
ignore:
  - benchmark/**
  - docs/**
  - sprig_functions_not_included_in_sprout.go
comment:
  behavior: new
  require_changes: true
